export const plans = {
    "Popular Plans": [
        { title: "₹299 Plan", description: "1.5GB/day, Unlimited Calls, 28 Days", details: "Best value plan with balanced data and calls.", fun: "Most Popular" },
        { title: "₹499 Plan", description: "2GB/day, OTT Subscription, 56 Days", details: "Perfect for entertainment and regular usage.", fun: "" },
        { title: "₹719 Plan", description: "1.5GB/day, 84 Days, Unlimited Calls", details: "Long-term plan for seamless connectivity.", fun: "Budget" },
        { title: "₹999 Plan", description: "3GB/day, Netflix Subscription, 84 Days", details: "Best for binge-watchers and heavy users.", fun: "" },
        { title: "₹149 Plan", description: "1GB/day, Unlimited Calls, 20 Days", details: "Budget-friendly option for essential communication.", fun: "" },
        { title: "₹349 Plan", description: "1.5GB/day, SonyLIV Subscription, 30 Days", details: "Entertainment-focused plan with popular streaming.", fun: "Budget" },
        { title: "₹599 Plan", description: "2GB/day, Disney+ Hotstar, 60 Days", details: "Premium plan for sports and movies.", fun: "Most Popular" },
        { title: "₹799 Plan", description: "2.5GB/day, Amazon Prime, 70 Days", details: "Value-packed plan with added benefits.", fun: "" },
        { title: "₹1199 Plan", description: "3GB/day, Netflix & Prime, 90 Days", details: "Ultimate entertainment plan for long-term usage.", fun: "Budget" },
        { title: "₹199 Plan", description: "1.5GB/day, Unlimited Calls, 28 Days", details: "Affordable plan with decent data and calling benefits.", fun: "Most Popular" },
        { title: "₹399 Plan", description: "2GB/day, Zee5 Subscription, 56 Days", details: "Regional entertainment plan with diverse content.", fun: "" },
        { title: "₹699 Plan", description: "1.5GB/day, 84 Days, Unlimited Calls + SMS", details: "Comprehensive plan with calling, data, and messaging.", fun: "" },
        { title: "₹899 Plan", description: "3GB/day, Hotstar VIP, 84 Days", details: "Sports-centric plan with live streaming access.", fun: "" },
        { title: "₹1299 Plan", description: "4GB/day, Netflix & SonyLIV, 90 Days", details: "High-data plan for heavy users and entertainment lovers.", fun: "" }
    ],
    "Data Plans": [
        { title: "₹19 Plan", description: "1GB for 1 Day", details: "Short-term data pack for emergency use.", fun: "Budget" },
        { title: "₹98 Plan", description: "6GB for 28 Days", details: "Extra data booster for heavy users.", fun: "" },
        { title: "₹251 Plan", description: "50GB for 30 Days", details: "Bulk data plan for professionals and gamers.", fun: "Most Popular" },
        { title: "₹499 Plan", description: "100GB for 60 Days", details: "High-speed data plan for work and streaming.", fun: "" },
        { title: "₹58 Plan", description: "3GB for 7 Days", details: "Weekly data pack for moderate usage.", fun: "Budget" },
        { title: "₹148 Plan", description: "12GB for 28 Days", details: "Mid-range data plan for regular browsing.", fun: "" },
        { title: "₹398 Plan", description: "75GB for 45 Days", details: "High-data plan for streaming and downloading.", fun: "Most Popular" },
        { title: "₹798 Plan", description: "200GB for 90 Days", details: "Large data plan for heavy users and multiple devices.", fun: "" },
        { title: "₹28 Plan", description: "2GB for 3 Days", details: "Quick data top-up for short-term needs.", fun: "Budget" },
        { title: "₹78 Plan", description: "5GB for 14 Days", details: "Flexible data pack for occasional use.", fun: "" },
        { title: "₹198 Plan", description: "30GB for 30 Days", details: "Balanced data plan for daily browsing and social media.", fun: "" },
        { title: "₹348 Plan", description: "60GB for 60 Days", details: "High-value data plan for streaming and gaming.", fun: "" },
        { title: "₹648 Plan", description: "150GB for 90 Days", details: "Long-term data plan for uninterrupted connectivity.", fun: "Most Popular" },
        { title: "₹998 Plan", description: "300GB for 120 Days", details: "Massive data plan for power users and data-intensive tasks.", fun: "" }
    ],
    "Validity Plans": [
        { title: "₹155 Plan", description: "Unlimited Calls, 1GB, 24 Days", details: "Basic plan for calls and minimal data use.", fun: "Most Popular" },
        { title: "₹395 Plan", description: "Unlimited Calls, 6GB, 84 Days", details: "Best for long-term calling needs.", fun: "Budget" },
        { title: "₹1799 Plan", description: "Unlimited Calls, 24GB, 365 Days", details: "Annual plan for worry-free usage.", fun: "Most Popular" },
        { title: "₹99 Plan", description: "Unlimited Calls, 500MB, 14 Days", details: "Entry-level plan for basic communication.", fun: "" },
        { title: "₹249 Plan", description: "Unlimited Calls, 3GB, 56 Days", details: "Balanced plan for calling and moderate data use.", fun: "" },
        { title: "₹699 Plan", description: "Unlimited Calls, 12GB, 180 Days", details: "Half-yearly plan for extended validity.", fun: "Budget" },
        { title: "₹1199 Plan", description: "Unlimited Calls, 36GB, 365 Days", details: "Long-term plan with generous data allowance.", fun: "Most Popular" },
        { title: "₹79 Plan", description: "Unlimited Calls, 200MB, 7 Days", details: "Short-term validity plan for emergency calling.", fun: "" },
        { title: "₹199 Plan", description: "Unlimited Calls, 2GB, 28 Days", details: "Affordable validity plan with decent data.", fun: "" },
        { title: "₹499 Plan", description: "Unlimited Calls, 8GB, 112 Days", details: "Mid-term validity plan with sufficient data.", fun: "Budget" },
        { title: "₹999 Plan", description: "Unlimited Calls, 18GB, 270 Days", details: "Long-validity plan with ample data for regular use.", fun: "" },
        { title: "₹129 Plan", description: "Unlimited Calls, 750MB, 21 Days", details: "Budget-friendly validity plan with basic data.", fun: "" },
        { title: "₹299 Plan", description: "Unlimited Calls, 4GB, 84 Days", details: "Value-for-money validity plan with good data.", fun: "" }
    ],
    "Unlimited Data Plans": [
        { title: "₹599 Plan", description: "Unlimited 5G Data, 84 Days", details: "Best for ultra-high-speed browsing.", fun: "Most Popular" },
        { title: "₹799 Plan", description: "Unlimited 4G Data, 84 Days", details: "Heavy usage plan with no data cap.", fun: "" },
        { title: "₹1499 Plan", description: "Truly Unlimited Data, 365 Days", details: "Ultimate long-term data freedom plan.", fun: "Budget" },
        { title: "₹499 Plan", description: "Unlimited Data (Fair Usage), 56 Days", details: "High-speed data with fair usage policy.", fun: "Most Popular" },
        { title: "₹699 Plan", description: "Unlimited Data (Fair Usage), 112 Days", details: "Extended validity with fair usage policy.", fun: "" },
        { title: "₹999 Plan", description: "Unlimited Data (Fair Usage), 180 Days", details: "Longer validity with fair usage policy.", fun: "" },
        { title: "₹1999 Plan", description: "Truly Unlimited Data, 365 Days + OTT", details: "Annual plan with unlimited data and streaming benefits.", fun: "" },
        { title: "₹399 Plan", description: "Unlimited Data (Fair Usage), 28 Days", details: "Affordable unlimited plan with fair usage limits.", fun: "Budget" },
        { title: "₹549 Plan", description: "Unlimited Data (Fair Usage), 70 Days", details: "Flexible unlimited plan with moderate validity.", fun: "" },
        { title: "₹849 Plan", description: "Unlimited Data (Fair Usage), 150 Days", details: "Long-term unlimited plan with fair usage policy.", fun: "" },
        { title: "₹1299 Plan", description: "Truly Unlimited Data, 200 Days", details: "High-validity unlimited plan for consistent usage.", fun: "" },
        { title: "₹299 Plan", description: "Unlimited Data (Fair Usage), 20 Days", details: "Budget-friendly unlimited plan for short-term use.", fun: "" },
        { title: "₹449 Plan", description: "Unlimited Data (Fair Usage), 45 Days", details: "Mid-range unlimited plan with decent validity.", fun: "Budget" },
        { title: "₹749 Plan", description: "Unlimited Data (Fair Usage), 100 Days", details: "Value unlimited plan for extended usage.", fun: "" }
    ]
};
